server.port=8086
spring.application.name=prod-eng-service
mongodb.connection.url=${MONGODB_CONNECTION_URL:${MONGODB_CONECTION_URL:mongodb://localhost:27017}}
mongodb.database.name=${MONGODB_DATABASE_NAME:autoservice}

# Actuator configuration for Prometheus metrics
management.endpoints.web.exposure.include=prometheus
management.metrics.export.prometheus.enabled=true
